---
- hosts: all
  gather_facts: no
  tasks:
    - name: Prepare nodepool instance
      block:
        - name: Install required packages
          yum:
            name:
              - createrepo
              - mock
              - python-jinja2
              - rpm-build
              - rpmdevtools

        - name: Add ci users in mock group
          user:
            name: zuul-worker
            group: mock
            append: yes
      become: true
