- hosts: all
  vars:
    project_dir: "{{ zuul.project.src_dir }}/"
  tasks:
    - include_role:
        name: koji-conf

    # Symlink does not work when npm link to parent file directory
    - name: Install node_modules
      command: "mv /usr/libexec/shake/node_modules {{ project_dir }}/node_modules"

    - name: Run yarn install
      command: yarn install --no-lockfile --offline
      args:
        chdir: "{{ project_dir }}"

    - name: Run yarn build
      command: yarn build
      args:
        chdir: "{{ project_dir }}"

    - name: Run yarn dist
      command: yarn dist
      args:
        chdir: "{{ project_dir }}"

    - name: Create tarball
      command: tar czf HEAD.tar.gz dist/
      args:
        chdir: "{{ project_dir }}"

    - include_role:
        name: simple-srpm-build

    - include_role:
        name: koji-build
