- hosts: all
  vars:
    project_dir: "{{ zuul.project.src_dir }}/"
  tasks:
    - include_role:
        name: koji-conf

    # Symlink does not work when npm link to parent file directory
    - name: Install node_modules
      command: "mv /usr/libexec/shake/node_modules {{ project_dir }}/node_modules"
      when: use_shake

    - name: Check if yarn archive exists
      stat:
        path: "{{ project_dir }}/yarn.lock.bz2"
      register: _yarn_archive

    - name: Extract yarn archive if exists
      shell: |
        cat {{ project_dir }}/yarn.lock.bz2 | bzip2 -d > {{ project_dir }}/yarn.lock
      when: _yarn_archive.stat.exists

    - name: Run yarn install
      command: |
        yarn install {% if yarn_no_lockfile %} --no-lockfile {% endif %} {% if yarn_offline %} --offline {% endif %}
      args:
        chdir: "{{ project_dir }}"

    - name: Run yarn build
      command: yarn build
      args:
        chdir: "{{ project_dir }}"
      when: yarn_build

    - name: Run yarn dist
      command: yarn dist
      args:
        chdir: "{{ project_dir }}"
      when: yarn_dist

    - name: Create tarball
      command: |
        tar czf HEAD.tgz {% if yarn_dist %} dist/ {% else %} node_modules/ {% endif %}
      args:
        chdir: "{{ project_dir }}"

    - include_role:
        name: simple-srpm-build

    - include_role:
        name: koji-build
