- hosts: all
  vars:
    project_dir: "{{ zuul.project.src_dir }}/"
  tasks:
    - name: Run pnpm install "{{ pnpm_install | default ('') }}"
      command: "pnpm install {{ pnpm_install }}"
      args:
        chdir: "{{ project_dir }}"

    - name: Run pnpm build
      command: pnpm build
      args:
        chdir: "{{ project_dir }}"

    - name: Run pnpm dist
      command: pnpm dist
      args:
        chdir: "{{ project_dir }}"

    - name: Create tarball
      command: tar czf HEAD.tgz dist/
      args:
        chdir: "{{ project_dir }}"

    - include_role:
        name: koji-conf

    - include_role:
        name: simple-srpm-build

    - include_role:
        name: koji-build
