---
- hosts: all
  vars:
    projects_list_query: "projects[*].name"
    projects_list: "{{ zuul | json_query(projects_list_query) }}"
    projects_args: >
        {% for project in projects_list %}--project {{ project }} {% endfor %}
    sfinfo_path_query: "projects[?name=='software-factory/sfinfo'].src_dir"
    sfinfo_path: "{{ (zuul | json_query(sfinfo_path_query))[0] }}"
    sfnamespace_path: "{{ sfinfo_path | dirname | dirname }}"
  tasks:
    - name: Copy rpm-gpg keys
      become: yes
      command: "rsync -a {{ sfinfo_path }}/rpm-gpg/ /etc/pki/rpm-gpg/"

    - name: Run zuul_rpm_build.py
      command: >
        ./software-factory/sfinfo/zuul_rpm_build.py \
            --distro-info ./software-factory/sfinfo/sf-{{ zuul.branch }}.yaml \
            --zuulv3 {{ projects_args }}
      args:
        chdir: "{{ sfnamespace_path }}"

    - name: Fetch zuul-rpm-build repository
      synchronize:
        src: "{{ sfnamespace_path }}/zuul-rpm-build/"
        dest: "{{ zuul.executor.log_root }}/buildset/"
        mode: pull
